### ISSUE TITLE
cros pluginn issue with redmine_repobrowser

### ISSUE THREAD

**Issue by cforce** [bdemirkir/sidebar_hide#22]
The sidebar button inside repo browser

![image](https://f.cloud.github.com/assets/393286/1308283/dbc5b9fe-31cb-11e3-9525-97700af72ccc.png)

see https://github.com/gilbertf/redmine_repobrowser/issues/12

**Comment by bdemirkir** [comment]
This plugins is not actively maintained anymore. I'm closing this report. Feel free to reopen it if you really need it.
