### ISSUE TITLE
"Internal error" after installing plugin

### ISSUE THREAD

**Issue by alexander-st** [bdemirkir/sidebar_hide#38]
I saw the plugin and wanted to test it. I installed it on my local machine and everything worked well.
Then I installed it on our server and Redmine was not working anymore. I got an "Internal error"
![sidebar_hide](https://cloud.githubusercontent.com/assets/10597540/6439861/ee74e2f6-c0df-11e4-9e56-4930be301225.jpg)

Has someone an idea what I can do to get the plugin running on the server?

**Comment by bdemirkir** [comment]
Please check your error logs and share them first.

**Comment by alexander-st** [comment]
OK. Which error log do you need and where can I find it.

Sorry I am new to this all.

Thank you for your help!!!

**Comment by bdemirkir** [comment]
You should have a production.log file in Redmine folder. If you're using webrick (simple development server), you can see the errors on the console too.

**Comment by alexander-st** [comment]
I hope I got the right part of the production.log

Started GET "/redmine/my/page_layout" for 46.43.110.107 at 2015-03-02 12:54:11 +0200
Processing by MyController#page_layout as HTML
  Current user: alex (id=1)
  Rendered issues/_list_simple.html.erb (15.6ms)
  Rendered my/blocks/_issuesassignedtome.html.erb (62.4ms)
  Rendered my/_block.html.erb (62.4ms)
  Rendered issues/_list_simple.html.erb (31.2ms)
  Rendered my/blocks/_issuesreportedbyme.html.erb (46.8ms)
  Rendered my/_block.html.erb (46.8ms)
  Rendered my/page_layout.html.erb within layouts/base (124.8ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (0.0ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (15.6ms)
Completed 500 Internal Server Error in 171.6ms

ActionView::Template::Error (Missing partial sidebar/hideButton_partial with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}. Searched in:
  * "C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/plugins/redmine_watcher_groups/app/views"
  * "C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/plugins/redmine_landing_page/app/views"
  * "C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/plugins/redmine_ckeditor/app/views"
  * "C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/plugins/clipboard_image_paste/app/views"
  * "C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/app/views"
  * "C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/kaminari-0.16.1/app/views"
  * "C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rich-1.4.6/app/views"
):
    56:         <%= view_layouts_base_sidebar_hook_response %>
    57:     </div>
    58: 
    59:     <div id="content">
    60:         <%= render_flash_messages %>
    61:         <%= yield %>
    62:         <%= call_hook :view_layouts_base_content %>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/layouts/base.html.erb:59:in `_app_views_layouts_base_html_erb___26349076_59400684'
  app/controllers/application_controller.rb:465:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:463:in `render_error'
  app/controllers/application_controller.rb:451:in `render_404'
  app/controllers/application_controller.rb:475:in `missing_template'


Started GET "/redmine/" for 127.0.0.1 at 2015-03-02 12:55:17 +0200
Processing by WelcomeController#index as HTML
  Current user: anonymous
Redirected to http://localhost/redmine/login?back_url=http%3A%2F%2Flocalhost%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 52.0ms (ActiveRecord: 2.0ms)
Started GET "/redmine/login?back_url=http%3A%2F%2Flocalhost%2Fredmine%2F" for 127.0.0.1 at 2015-03-02 12:55:17 +0200
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://localhost/redmine/"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (7.0ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (3.0ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (2.0ms)
Completed 500 Internal Server Error in 97.1ms

ActionView::Template::Error (Missing partial sidebar/hideButton_partial with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}. Searched in:
  * "C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/plugins/redmine_watcher_groups/app/views"
  * "C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/plugins/redmine_landing_page/app/views"
  * "C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/plugins/redmine_ckeditor/app/views"
  * "C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/plugins/clipboard_image_paste/app/views"
  * "C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/app/views"
  * "C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/kaminari-0.16.1/app/views"
  * "C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rich-1.4.6/app/views"
):
    56:         <%= view_layouts_base_sidebar_hook_response %>
    57:     </div>
    58: 
    59:     <div id="content">
    60:         <%= render_flash_messages %>
    61:         <%= yield %>
    62:         <%= call_hook :view_layouts_base_content %>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/layouts/base.html.erb:59:in `_app_views_layouts_base_html_erb___26349076_59400684'
  app/controllers/application_controller.rb:465:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:463:in `render_error'
  app/controllers/application_controller.rb:451:in `render_404'
  app/controllers/application_controller.rb:475:in `missing_template'

**Comment by bdemirkir** [comment]
Thanks. It looks like you didn't install the plugin on the right directory. init.rb file should be located at C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/plugins/sidebar_hide/

**Comment by alexander-st** [comment]
You are right, It was my fault, It seems I was to tired on that day. I am very sorry I took your time for such a stupid mistake.
Thank you for your time!!!

**Comment by bdemirkir** [comment]
No problem :smile: It happens all the time.
