### ISSUE TITLE
What license is this released under?

### ISSUE THREAD

**Issue by ampmmn** [bdemirkir/sidebar_hide#41]
Hi,
This plugin is so useful, and I'd like to use it in the place where I work.
But they pay attention to the license plugin is released under.
So I looked into the repository, but I didn't see any license terms mentioned in the repository.
Could you please add one?
Thanks.

**Comment by bdemirkir** [comment]
Here's the license (spoiler: MIT). I think it'll be more than enough to install on your work environment :wink:

**Comment by ampmmn** [comment]
Awesome! Thanks!
