### ISSUE TITLE
" + " menu in Redmine 3.3 not working with this plugin

### ISSUE THREAD

**Issue by dinkel** [bdemirkir/sidebar_hide#43]
Hi,

When installing this plugin, the new " + " menu in Redmine 3.3.0 will not show up. It seems to be related to the

```
#content {
    position: relative;
}
```

set in `sidebar_hide.css`.

**Comment by nanego** [comment]
Hi
This css code also hide the dropdown menu that should be visible when clicking on the "Highlighted code" button in the textfield toolbar.

**Comment by bdemirkir** [comment]
Thank you for your contributions! Merged. Will release the new version shortly.
