### ISSUE TITLE
Compatibility with Redmine 3.3.0

### ISSUE THREAD

**Issue by ehvidal** [bdemirkir/sidebar_hide#44]
Thank you very much for your fine job! I have been using your plugin for the last 5 years and I think it's awesome.

Now I'm planning to migrate my Redmine to 3.3.0, so my question is, are you planning to make your plugin compatible with Redmine 3.3.0 soon? Do you have some idea about when it will be published?

Again, thank you very much for your excellent work!

**Comment by tostasqb** [comment]
I forked and used @alexandermeindl repo, who has done a great job resolving that. Submitted that fork for a pull request just now #45

**Comment by bdemirkir** [comment]
Thank you @tostasqb and @alexandermeindl for your contributions! I'll check and try to merge your PR.

**Comment by rompic** [comment]
is there a timeframe for this to be released?
best,Roman

**Comment by bdemirkir** [comment]
Thank you for your contributions! Merged. Will release the new version shortly.
